### ISSUE TITLE
No DOI for downloaded data

### ISSUE THREAD

**Issue by simonrolph** [BioDT/uc-ces#27]
Because we use occ_data (which is a faster version of occ_search) we don't currently generate a doi for the downloaded data.

We should be using occ_download https://docs.ropensci.org/rgbif/reference/occ_download.html as this should generate a doi with the download.

However, it requires authentication (username/password) which we will need to provide in a gitignored .environ file.

**Comment by DylanCarbone** [comment]
Hi Simon,

I have fixed this in the latest commit. We can review my changes in our next meeting, thanks
