### ISSUE TITLE
Move R code for autogenerating ODMAP into separate .R script

### ISSUE THREAD

**Issue by simonrolph** [BioDT/uc-ces#32]
Take lines 418 onwards https://github.com/BioDT/uc-ces/blob/main/biodiversity_model/biodiversity_model_workflow_flexsdm_ODMAP.Rmd#L418 and turn into a function that can be placed in a different R file. Suggested file name `generate_odmap.R` with a function `generate_odmap()`? Not sure what arguments the function would need?

 I think it would be best to put the R file in this folder https://github.com/BioDT/uc-ces/tree/main/biodiversity_model/R

**Comment by DylanCarbone** [comment]
Hi @simonrolph,

Please see the render_ODMAP.r R file I have created [here](https://github.com/BioDT/uc-ces/blob/main/biodiversity_model/R/render_ODMAP.r). I've also included the helper functions that navigate the ODMAP dictionary to obtain element definitions.

The approach I have taken to ODMAP report generation here has been to specify each of the ODMAP IDs as function parameters, with the exception of fields that are generated automatically from objects obtained from the SDM model workflow. The ODMAP report generation chunk in the sdm workflow has also been shorted, [here](https://github.com/BioDT/uc-ces/blob/a4a7a21f6b324b45e6c351c5ae7146a17ec54673/biodiversity_model/biodiversity_model_workflow_flexsdm_ODMAP.Rmd#L421-L504).

Thanks,

Dylan
